[package]
name = "bookmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.7", features = ["derive"] }
nom = "7.1.3"

[[bin]]
name = "crossmarks"
path = "src/main.rs"
